name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - koputer
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (apt)
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake autoconf automake libtool pkg-config ninja-build

      - name: Build
        run: |
          make palera1n WITH_STATIC=1 BUILD_TYPE=Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: palera1n-linux
          path: |
            build/palera1n

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-15-intel
            arch: x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (brew)
        run: |
          brew update
          brew install cmake autoconf automake libtool pkg-config

      - name: Build
        run: |
          make palera1n WITH_STATIC=1 WITH_GUI=1 BUILD_TYPE=Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: palera1n-macos-${{ matrix.arch }}
          path: |
            build/palera1n.app

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            libtool
            openssl
            openssl-devel
            python-devel
            autoconf
            automake
            zip
            vim
            make
          update: true

      - name: Build
        shell: msys2 {0}
        run: |
          make palera1n_mingw WITH_STATIC=1 WITH_GUI=1 BUILD_TYPE=Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: palera1n-windows-x86_64
          path: |
            build/*.exe 
            build/*.dll
